/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author thiev
 */
public class Fenêtre_principale extends javax.swing.JFrame {

    /**
     * Creates new form Fenêtre_principale
     */
    public Fenêtre_principale() {
        initComponents();
        // TextBonjour.setText("Salut");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoutonBatard = new javax.swing.JButton();
        TextWarning = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TextBonjour = new javax.swing.JLabel();
        TextFieldprénom = new javax.swing.JTextField();
        BoutonValider = new javax.swing.JButton();
        TextAurevoir = new javax.swing.JLabel();
        Textmdp = new javax.swing.JLabel();
        TextSaisirmdp = new javax.swing.JLabel();
        TextFieldmdp = new javax.swing.JPasswordField();
        Bouton_x2 = new javax.swing.JButton();
        TextNombre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BoutonBatard.setText("Cliquez pour une insulte");
        BoutonBatard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonBatardActionPerformed(evt);
            }
        });

        TextWarning.setText("Attention");

        TextBonjour.setText("Entrez votre prénom");

        TextFieldprénom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldprénomActionPerformed(evt);
            }
        });

        BoutonValider.setText("Valider");
        BoutonValider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonValiderActionPerformed(evt);
            }
        });

        TextAurevoir.setText("Votre prénom");

        Textmdp.setText("Votre mdp");

        TextSaisirmdp.setText("Entrez votre mdp");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BoutonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Textmdp)
                                    .addComponent(TextAurevoir))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TextBonjour)
                        .addGap(42, 42, 42)
                        .addComponent(TextFieldprénom, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(TextSaisirmdp)))
                .addGap(44, 44, 44)
                .addComponent(TextFieldmdp, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldprénom, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextSaisirmdp)
                    .addComponent(TextFieldmdp, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextBonjour))
                .addGap(37, 37, 37)
                .addComponent(BoutonValider, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TextAurevoir)
                .addGap(18, 18, 18)
                .addComponent(Textmdp)
                .addGap(31, 31, 31))
        );

        Bouton_x2.setText("Cliquez pour multiplier par 2 le nombre");
        Bouton_x2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_x2ActionPerformed(evt);
            }
        });

        TextNombre.setText("1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 39, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BoutonBatard, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bouton_x2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextWarning)
                        .addGap(204, 204, 204))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(37, 37, 37)
                .addComponent(TextNombre)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextWarning)
                    .addComponent(Bouton_x2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(BoutonBatard, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonValiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonValiderActionPerformed
        // TODO add your handling code here:
        String nomUtilisateur = TextFieldprénom.getText();
        String MotDePasse = TextFieldmdp.getText();
        TextBonjour.setText("Vous avez appuyé sur le bouton");
        TextAurevoir.setText("Vous vous appelez "+ nomUtilisateur);
        Textmdp.setText("Votre mot de passe est " + MotDePasse);
    }//GEN-LAST:event_BoutonValiderActionPerformed

    private void TextFieldprénomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldprénomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldprénomActionPerformed

    private void BoutonBatardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonBatardActionPerformed
        // TODO add your handling code here:
        String tab[] = new String[5];
        tab[0] = "Connard !";
        tab[1] = "Batard !";
        tab[2] = "Enculé !";
        tab[3] = "Fils de pute !";
        tab[4] = "Grosse merde !";
        int a = (int)(Math.random()*5);
        TextWarning.setText(tab[a]);
    }//GEN-LAST:event_BoutonBatardActionPerformed
int a = 1;
    private void Bouton_x2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_x2ActionPerformed
        // TODO add your handling code here:
        a = 2*a;
        String b = a + "";
        TextNombre.setText(b);
                
    }//GEN-LAST:event_Bouton_x2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenêtre_principale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenêtre_principale().setVisible(true);
            }
        });
        System.out.println("Cool");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BoutonBatard;
    private javax.swing.JButton BoutonValider;
    private javax.swing.JButton Bouton_x2;
    private javax.swing.JLabel TextAurevoir;
    private javax.swing.JLabel TextBonjour;
    private javax.swing.JPasswordField TextFieldmdp;
    private javax.swing.JTextField TextFieldprénom;
    private javax.swing.JLabel TextNombre;
    private javax.swing.JLabel TextSaisirmdp;
    private javax.swing.JLabel TextWarning;
    private javax.swing.JLabel Textmdp;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
