/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onitama_thievon;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author thiev
 */
public class FenetreMusique extends javax.swing.JFrame {

    /**
     * Creates new form FenetreMusique
     */
    public FenetreMusique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnOP1 = new javax.swing.JButton();
        BtnOP2 = new javax.swing.JButton();
        BtnOP3 = new javax.swing.JButton();
        BtnOP4 = new javax.swing.JButton();
        BtnOP5 = new javax.swing.JButton();
        BtnOP6 = new javax.swing.JButton();
        BtnOP7 = new javax.swing.JButton();
        BtnOP8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnOP9 = new javax.swing.JButton();
        BtnOP10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnThemeJonathan = new javax.swing.JButton();
        BtnThemeJoseph = new javax.swing.JButton();
        BtnThemeJotaro = new javax.swing.JButton();
        BtnThemeJosuke = new javax.swing.JButton();
        BtnThemeGiorno = new javax.swing.JButton();
        BtnThemeJolyne = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtnOP1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP1.setText("Opening 1");
        BtnOP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP1ActionPerformed(evt);
            }
        });

        BtnOP2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP2.setText("Opening 2");
        BtnOP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP2ActionPerformed(evt);
            }
        });

        BtnOP3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP3.setText("Opening 3");
        BtnOP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP3ActionPerformed(evt);
            }
        });

        BtnOP4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP4.setText("Opening 4");
        BtnOP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP4ActionPerformed(evt);
            }
        });

        BtnOP5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP5.setText("Opening 5");
        BtnOP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP5ActionPerformed(evt);
            }
        });

        BtnOP6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP6.setText("Opening 6");
        BtnOP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP6ActionPerformed(evt);
            }
        });

        BtnOP7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP7.setText("Opening 7");
        BtnOP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP7ActionPerformed(evt);
            }
        });

        BtnOP8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP8.setText("Opening 8");
        BtnOP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setText("Sono Chi no Sadame");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setText("Bloody Stream");

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setText("Stand Proud");

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setText("Sono Chi no Kioku");

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setText("Crazy Noisy Bizarre Town");

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setText("Chase");

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setText("Fighting gold");

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setText("Great Days");

        BtnOP9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP9.setText("Opening 9");
        BtnOP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP9ActionPerformed(evt);
            }
        });

        BtnOP10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP10.setText("Opening 10");
        BtnOP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP10ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setText("Uragirimono requiem");

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setText("Stone Ocean");

        BtnThemeJonathan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeJonathan.setText("Jonathan's Theme");
        BtnThemeJonathan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeJonathanActionPerformed(evt);
            }
        });

        BtnThemeJoseph.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeJoseph.setText("Joseph's Theme");
        BtnThemeJoseph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeJosephActionPerformed(evt);
            }
        });

        BtnThemeJotaro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeJotaro.setText("Jotaro's Theme");
        BtnThemeJotaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeJotaroActionPerformed(evt);
            }
        });

        BtnThemeJosuke.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeJosuke.setText("Josuke's Theme");
        BtnThemeJosuke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeJosukeActionPerformed(evt);
            }
        });

        BtnThemeGiorno.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeGiorno.setText("Giorno's Theme");
        BtnThemeGiorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeGiornoActionPerformed(evt);
            }
        });

        BtnThemeJolyne.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeJolyne.setText("Jolyne's Theme");
        BtnThemeJolyne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeJolyneActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setText("Opening 11");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel11.setText("Heaven's Falling Down");

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel12.setText("Jojo's Bizarre Adventure OST");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnOP1)
                    .addComponent(BtnOP2)
                    .addComponent(BtnOP3)
                    .addComponent(BtnOP4)
                    .addComponent(BtnOP5)
                    .addComponent(BtnOP6)
                    .addComponent(BtnOP7)
                    .addComponent(BtnOP8)
                    .addComponent(BtnOP9)
                    .addComponent(BtnOP10)
                    .addComponent(jButton1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnThemeJolyne)
                            .addComponent(BtnThemeGiorno)
                            .addComponent(BtnThemeJotaro)
                            .addComponent(BtnThemeJoseph)
                            .addComponent(BtnThemeJonathan)
                            .addComponent(BtnThemeJosuke))
                        .addGap(347, 347, 347))))
            .addGroup(layout.createSequentialGroup()
                .addGap(428, 428, 428)
                .addComponent(jLabel12)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnOP1)
                            .addComponent(jLabel1))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnThemeJonathan)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnOP2)
                            .addComponent(jLabel2))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnOP3)
                            .addComponent(jLabel3)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnThemeJoseph)
                        .addGap(47, 47, 47)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnOP4)
                            .addComponent(jLabel4)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnThemeJotaro)
                        .addGap(25, 25, 25)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnOP5)
                            .addComponent(jLabel5))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BtnThemeJosuke)
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOP6)
                    .addComponent(jLabel6))
                .addGap(7, 7, 7)
                .addComponent(BtnThemeGiorno)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOP7)
                    .addComponent(jLabel8))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOP8)
                    .addComponent(jLabel7)
                    .addComponent(BtnThemeJolyne))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOP9)
                    .addComponent(jLabel9))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnOP10)
                    .addComponent(jLabel10))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel11))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP1ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Sono Chi no Sadame.wav");
    }//GEN-LAST:event_BtnOP1ActionPerformed

    private void BtnOP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP4ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Sono chi no Kioku.wav");
    }//GEN-LAST:event_BtnOP4ActionPerformed

    private void BtnOP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP5ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Crazy Noisy Bizarre Town.wav");
    }//GEN-LAST:event_BtnOP5ActionPerformed

    private void BtnOP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP2ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Bloody Stream.wav");
    }//GEN-LAST:event_BtnOP2ActionPerformed

    private void BtnOP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP3ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Stand Proud.wav");
    }//GEN-LAST:event_BtnOP3ActionPerformed

    private void BtnOP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP6ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Chase.wav");
    }//GEN-LAST:event_BtnOP6ActionPerformed

    private void BtnOP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP7ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Great Days.wav");
    }//GEN-LAST:event_BtnOP7ActionPerformed

    private void BtnOP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP8ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Fighting Gold.wav");
    }//GEN-LAST:event_BtnOP8ActionPerformed

    private void BtnOP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP9ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Uragirimono no requiem.wav");
    }//GEN-LAST:event_BtnOP9ActionPerformed

    private void BtnOP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP10ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Stone Ocean.wav");
    }//GEN-LAST:event_BtnOP10ActionPerformed

    private void BtnThemeJonathanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeJonathanActionPerformed
        // TODO add your handling code here:
        PlayMusic("Jonathan's Theme.wav");
    }//GEN-LAST:event_BtnThemeJonathanActionPerformed

    private void BtnThemeJosephActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeJosephActionPerformed
        // TODO add your handling code here:
        PlayMusic("Joseph's Theme.wav");
    }//GEN-LAST:event_BtnThemeJosephActionPerformed

    private void BtnThemeJotaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeJotaroActionPerformed
        // TODO add your handling code here:
        PlayMusic("Jotaro's Theme.wav");
    }//GEN-LAST:event_BtnThemeJotaroActionPerformed

    private void BtnThemeJosukeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeJosukeActionPerformed
        // TODO add your handling code here:
        PlayMusic("Josuke's Theme.wav");
    }//GEN-LAST:event_BtnThemeJosukeActionPerformed

    private void BtnThemeGiornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeGiornoActionPerformed
        // TODO add your handling code here:
        PlayMusic("Giorno's Theme.wav");
    }//GEN-LAST:event_BtnThemeGiornoActionPerformed

    private void BtnThemeJolyneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeJolyneActionPerformed
        // TODO add your handling code here:
        PlayMusic("Jolyne's Theme.wav");
    }//GEN-LAST:event_BtnThemeJolyneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Heaven's falling down.wav");
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public static void PlayMusic(String location) {
        try {
            File musicPath = new File(location);
            if(musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
            }
            else {
                System.out.println("Trouve pas le fichier");
            }
        }catch(Exception e) {
            
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreMusique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreMusique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreMusique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreMusique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreMusique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOP1;
    private javax.swing.JButton BtnOP10;
    private javax.swing.JButton BtnOP2;
    private javax.swing.JButton BtnOP3;
    private javax.swing.JButton BtnOP4;
    private javax.swing.JButton BtnOP5;
    private javax.swing.JButton BtnOP6;
    private javax.swing.JButton BtnOP7;
    private javax.swing.JButton BtnOP8;
    private javax.swing.JButton BtnOP9;
    private javax.swing.JButton BtnThemeGiorno;
    private javax.swing.JButton BtnThemeJolyne;
    private javax.swing.JButton BtnThemeJonathan;
    private javax.swing.JButton BtnThemeJoseph;
    private javax.swing.JButton BtnThemeJosuke;
    private javax.swing.JButton BtnThemeJotaro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
