/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onitama_thievon;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author thiev
 */
public class FenetreMusique extends javax.swing.JFrame {

    /**
     * Creates new form FenetreMusique
     */
    public FenetreMusique() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnOP1 = new javax.swing.JButton();
        BtnOP2 = new javax.swing.JButton();
        BtnOP3 = new javax.swing.JButton();
        BtnOP4 = new javax.swing.JButton();
        BtnOP5 = new javax.swing.JButton();
        BtnOP6 = new javax.swing.JButton();
        BtnOP7 = new javax.swing.JButton();
        BtnOP8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        BtnOP9 = new javax.swing.JButton();
        BtnOP10 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        BtnThemeJonathan = new javax.swing.JButton();
        BtnThemeJoseph = new javax.swing.JButton();
        BtnThemeJotaro = new javax.swing.JButton();
        BtnThemeJosuke = new javax.swing.JButton();
        BtnThemeGiorno = new javax.swing.JButton();
        BtnThemeJolyne = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtnQuitter = new javax.swing.JButton();
        BtnThemeDio = new javax.swing.JButton();
        BtnThemeKars = new javax.swing.JButton();
        BtnThemeKira = new javax.swing.JButton();
        BtnThemeDiavolo = new javax.swing.JButton();
        BtnThemePucci = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1160, 900));
        setPreferredSize(new java.awt.Dimension(1160, 900));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnOP1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP1.setText("Opening 1");
        BtnOP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP1ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        BtnOP2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP2.setText("Opening 2");
        BtnOP2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP2ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, -1, -1));

        BtnOP3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP3.setText("Opening 3");
        BtnOP3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP3ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOP3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, -1));

        BtnOP4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP4.setText("Opening 4");
        BtnOP4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP4ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOP4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, -1, -1));

        BtnOP5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP5.setText("Opening 5");
        BtnOP5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP5ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOP5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, -1, -1));

        BtnOP6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP6.setText("Opening 6");
        BtnOP6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP6ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOP6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        BtnOP7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP7.setText("Opening 7");
        BtnOP7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP7ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOP7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 510, -1, -1));

        BtnOP8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP8.setText("Opening 8");
        BtnOP8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP8ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOP8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 580, -1, -1));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sono Chi no Sadame");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bloody Stream");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Stand Proud");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sono Chi no Kioku");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Crazy Noisy Bizarre Town");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Chase");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fighting gold");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Great Days");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, -1, -1));

        BtnOP9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP9.setText("Opening 9");
        BtnOP9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP9ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOP9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 650, -1, -1));

        BtnOP10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnOP10.setText("Opening 10");
        BtnOP10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnOP10ActionPerformed(evt);
            }
        });
        getContentPane().add(BtnOP10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 720, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Uragirimono requiem");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 650, -1, -1));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Stone Ocean");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 720, -1, -1));

        BtnThemeJonathan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeJonathan.setText("Jonathan's Theme");
        BtnThemeJonathan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeJonathanActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemeJonathan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 90, 200, -1));

        BtnThemeJoseph.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeJoseph.setText("Joseph's Theme");
        BtnThemeJoseph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeJosephActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemeJoseph, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 160, 200, -1));

        BtnThemeJotaro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeJotaro.setText("Jotaro's Theme");
        BtnThemeJotaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeJotaroActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemeJotaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 230, 200, -1));

        BtnThemeJosuke.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeJosuke.setText("Josuke's Theme");
        BtnThemeJosuke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeJosukeActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemeJosuke, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 300, 200, -1));

        BtnThemeGiorno.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeGiorno.setText("Giorno's Theme");
        BtnThemeGiorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeGiornoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemeGiorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, 200, -1));

        BtnThemeJolyne.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeJolyne.setText("Jolyne's Theme");
        BtnThemeJolyne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeJolyneActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemeJolyne, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 200, -1));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton1.setText("Opening 11");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 790, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Heaven's Falling Down");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 790, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Jojo's Bizarre Adventure OST");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 24, -1, -1));

        BtnQuitter.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnQuitter.setText("Quitter");
        BtnQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnQuitterActionPerformed(evt);
            }
        });
        getContentPane().add(BtnQuitter, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 790, -1, -1));

        BtnThemeDio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeDio.setText("Dio's Theme");
        BtnThemeDio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeDioActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemeDio, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 510, 200, -1));

        BtnThemeKars.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeKars.setText("Kars's Theme");
        BtnThemeKars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeKarsActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemeKars, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 580, 200, -1));

        BtnThemeKira.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeKira.setText("Kira's Theme");
        BtnThemeKira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeKiraActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemeKira, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 650, 200, -1));

        BtnThemeDiavolo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemeDiavolo.setText("Diavolo's Theme");
        BtnThemeDiavolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemeDiavoloActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemeDiavolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 720, 200, -1));

        BtnThemePucci.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BtnThemePucci.setText("Pucci's Theme");
        BtnThemePucci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnThemePucciActionPerformed(evt);
            }
        });
        getContentPane().add(BtnThemePucci, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 790, 200, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Modern Wallpaper.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 900));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnOP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP1ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Sono Chi no Sadame.wav");
    }//GEN-LAST:event_BtnOP1ActionPerformed

    private void BtnOP4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP4ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Sono chi no Kioku.wav");
    }//GEN-LAST:event_BtnOP4ActionPerformed

    private void BtnOP5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP5ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Crazy Noisy Bizarre Town.wav");
    }//GEN-LAST:event_BtnOP5ActionPerformed

    private void BtnOP2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP2ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Bloody Stream.wav");
    }//GEN-LAST:event_BtnOP2ActionPerformed

    private void BtnOP3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP3ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Stand Proud.wav");
    }//GEN-LAST:event_BtnOP3ActionPerformed

    private void BtnOP6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP6ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Chase.wav");
    }//GEN-LAST:event_BtnOP6ActionPerformed

    private void BtnOP7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP7ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Great Days.wav");
    }//GEN-LAST:event_BtnOP7ActionPerformed

    private void BtnOP8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP8ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Fighting Gold.wav");
    }//GEN-LAST:event_BtnOP8ActionPerformed

    private void BtnOP9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP9ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Uragirimono no requiem.wav");
    }//GEN-LAST:event_BtnOP9ActionPerformed

    private void BtnOP10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnOP10ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Stone Ocean.wav");
    }//GEN-LAST:event_BtnOP10ActionPerformed

    private void BtnThemeJonathanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeJonathanActionPerformed
        // TODO add your handling code here:
        PlayMusic("Jonathan's Theme.wav");
    }//GEN-LAST:event_BtnThemeJonathanActionPerformed

    private void BtnThemeJosephActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeJosephActionPerformed
        // TODO add your handling code here:
        PlayMusic("Joseph's Theme.wav");
    }//GEN-LAST:event_BtnThemeJosephActionPerformed

    private void BtnThemeJotaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeJotaroActionPerformed
        // TODO add your handling code here:
        PlayMusic("Jotaro's Theme.wav");
    }//GEN-LAST:event_BtnThemeJotaroActionPerformed

    private void BtnThemeJosukeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeJosukeActionPerformed
        // TODO add your handling code here:
        PlayMusic("Josuke's Theme.wav");
    }//GEN-LAST:event_BtnThemeJosukeActionPerformed

    private void BtnThemeGiornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeGiornoActionPerformed
        // TODO add your handling code here:
        PlayMusic("Giorno's Theme.wav");
    }//GEN-LAST:event_BtnThemeGiornoActionPerformed

    private void BtnThemeJolyneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeJolyneActionPerformed
        // TODO add your handling code here:
        PlayMusic("Jolyne's Theme.wav");
    }//GEN-LAST:event_BtnThemeJolyneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PlayMusic("Heaven's falling down.wav");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BtnQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnQuitterActionPerformed
        // TODO add your handling code here:
        FenetreMusique.super.dispose();
    }//GEN-LAST:event_BtnQuitterActionPerformed

    private void BtnThemeDioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeDioActionPerformed
        // TODO add your handling code here:
        PlayMusic("Dio's Theme.wav");
    }//GEN-LAST:event_BtnThemeDioActionPerformed

    private void BtnThemeKarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeKarsActionPerformed
        // TODO add your handling code here:
        PlayMusic("Kars's Theme.wav");
    }//GEN-LAST:event_BtnThemeKarsActionPerformed

    private void BtnThemeKiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeKiraActionPerformed
        // TODO add your handling code here:
        PlayMusic("Kira's Theme.wav");
    }//GEN-LAST:event_BtnThemeKiraActionPerformed

    private void BtnThemeDiavoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemeDiavoloActionPerformed
        // TODO add your handling code here:
        PlayMusic("Diavolo's Theme.wav");
    }//GEN-LAST:event_BtnThemeDiavoloActionPerformed

    private void BtnThemePucciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnThemePucciActionPerformed
        // TODO add your handling code here:
        PlayMusic("Pucci's Theme.wav");
    }//GEN-LAST:event_BtnThemePucciActionPerformed

    
    public static void PlayMusic(String location) {
        try {
            File musicPath = new File(location);
            if(musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
            }
            else {
                System.out.println("Trouve pas le fichier");
            }
        }catch(Exception e) {
            
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreMusique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreMusique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreMusique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreMusique.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreMusique().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnOP1;
    private javax.swing.JButton BtnOP10;
    private javax.swing.JButton BtnOP2;
    private javax.swing.JButton BtnOP3;
    private javax.swing.JButton BtnOP4;
    private javax.swing.JButton BtnOP5;
    private javax.swing.JButton BtnOP6;
    private javax.swing.JButton BtnOP7;
    private javax.swing.JButton BtnOP8;
    private javax.swing.JButton BtnOP9;
    private javax.swing.JButton BtnQuitter;
    private javax.swing.JButton BtnThemeDiavolo;
    private javax.swing.JButton BtnThemeDio;
    private javax.swing.JButton BtnThemeGiorno;
    private javax.swing.JButton BtnThemeJolyne;
    private javax.swing.JButton BtnThemeJonathan;
    private javax.swing.JButton BtnThemeJoseph;
    private javax.swing.JButton BtnThemeJosuke;
    private javax.swing.JButton BtnThemeJotaro;
    private javax.swing.JButton BtnThemeKars;
    private javax.swing.JButton BtnThemeKira;
    private javax.swing.JButton BtnThemePucci;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
