/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onitama_thievon;

import javax.accessibility.AccessibleContext;
import javax.swing.JRootPane;

/**
 *
 * @author thiev
 */
public class Fenetre_choixJoueurs extends javax.swing.JFrame {
    
    Joueur[] ListeJoueurs = new Joueur[2];
    int cptJoueurs = 0;
    /**
     * Creates new form Fenetre_choixJoueurs
     */
    public Fenetre_choixJoueurs() {
        initComponents();
        BoutonLancerPartie.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        Bouton_Jolyne = new javax.swing.JButton();
        Bouton_Jonathan = new javax.swing.JButton();
        Bouton_Joseph = new javax.swing.JButton();
        Bouton_Jotaro = new javax.swing.JButton();
        Bouton_Josuke = new javax.swing.JButton();
        Bouton_Giorno = new javax.swing.JButton();
        Bouton_Pucci = new javax.swing.JButton();
        Bouton_Dio = new javax.swing.JButton();
        Bouton_Kars = new javax.swing.JButton();
        Bouton_Kira = new javax.swing.JButton();
        Bouton_Diavolo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LabelJoueur1 = new javax.swing.JLabel();
        BoutonLancerPartie = new javax.swing.JToggleButton();
        LabelJoueur2 = new javax.swing.JLabel();
        LabelJ1 = new javax.swing.JLabel();
        LabelJ2 = new javax.swing.JLabel();
        Label_Pucci = new javax.swing.JLabel();
        Label_Jonathan = new javax.swing.JLabel();
        Label_Joseph = new javax.swing.JLabel();
        Label_Jotaro = new javax.swing.JLabel();
        Label_Josuke = new javax.swing.JLabel();
        Label_Giorno = new javax.swing.JLabel();
        Label_Diavolo = new javax.swing.JLabel();
        Label_Kira = new javax.swing.JLabel();
        Label_Kars = new javax.swing.JLabel();
        Label_Dio = new javax.swing.JLabel();
        Label_Jolyne = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Jotaro Kujo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bouton_Jolyne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jolyne_bt.jpg"))); // NOI18N
        Bouton_Jolyne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JolyneActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Jolyne, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 740, -1, -1));

        Bouton_Jonathan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jonathan_bt.jpg"))); // NOI18N
        Bouton_Jonathan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JonathanActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Jonathan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        Bouton_Joseph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Joseph_bt.jpg"))); // NOI18N
        Bouton_Joseph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JosephActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Joseph, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        Bouton_Jotaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jotaro_bt.jpg"))); // NOI18N
        Bouton_Jotaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JotaroActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Jotaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 40, -1, -1));

        Bouton_Josuke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Josuke_bt.jpg"))); // NOI18N
        Bouton_Josuke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JosukeActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Josuke, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 40, -1, -1));

        Bouton_Giorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Giorno_bt.jpg"))); // NOI18N
        Bouton_Giorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_GiornoActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Giorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 40, -1, -1));

        Bouton_Pucci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pucci_bt.jpg"))); // NOI18N
        Bouton_Pucci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_PucciActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Pucci, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 740, -1, -1));

        Bouton_Dio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dio_bt.jpg"))); // NOI18N
        Bouton_Dio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_DioActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Dio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, -1, -1));

        Bouton_Kars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kars_bt.jpg"))); // NOI18N
        Bouton_Kars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_KarsActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Kars, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        Bouton_Kira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/kira_bt.jpg"))); // NOI18N
        Bouton_Kira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_KiraActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Kira, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 400, -1, -1));

        Bouton_Diavolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Diavolo_bt.jpg"))); // NOI18N
        Bouton_Diavolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_DiavoloActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Diavolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 400, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LabelJoueur1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        LabelJoueur1.setText("Joueur 1 :");

        BoutonLancerPartie.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BoutonLancerPartie.setText("Lancer une partie");
        BoutonLancerPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonLancerPartieActionPerformed(evt);
            }
        });

        LabelJoueur2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        LabelJoueur2.setText("Joueur 2 :");

        LabelJ1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        LabelJ2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJoueur1)
                    .addComponent(LabelJoueur2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelJ2)
                    .addComponent(LabelJ1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(57, Short.MAX_VALUE)
                .addComponent(BoutonLancerPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJoueur1)
                    .addComponent(LabelJ1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJoueur2)
                    .addComponent(LabelJ2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addComponent(BoutonLancerPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 380, 310));

        Label_Pucci.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Pucci.setForeground(new java.awt.Color(255, 255, 255));
        Label_Pucci.setText("Enrico Pucci");
        getContentPane().add(Label_Pucci, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 720, -1, -1));

        Label_Jonathan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Jonathan.setForeground(new java.awt.Color(255, 255, 255));
        Label_Jonathan.setText("Jonathan Joestar");
        getContentPane().add(Label_Jonathan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        Label_Joseph.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Joseph.setForeground(new java.awt.Color(255, 255, 255));
        Label_Joseph.setText("Joseph Joestar");
        getContentPane().add(Label_Joseph, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, -1, -1));

        Label_Jotaro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Jotaro.setForeground(new java.awt.Color(255, 255, 255));
        Label_Jotaro.setText("Jotaro Kujo");
        getContentPane().add(Label_Jotaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 20, -1, -1));

        Label_Josuke.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Josuke.setForeground(new java.awt.Color(255, 255, 255));
        Label_Josuke.setText("Josuke Higashikata");
        getContentPane().add(Label_Josuke, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 20, -1, -1));

        Label_Giorno.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Giorno.setForeground(new java.awt.Color(255, 255, 255));
        Label_Giorno.setText("Giorno Giovanna");
        getContentPane().add(Label_Giorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1670, 20, -1, -1));

        Label_Diavolo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Diavolo.setForeground(new java.awt.Color(255, 255, 255));
        Label_Diavolo.setText("Diavolo");
        getContentPane().add(Label_Diavolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1700, 380, -1, -1));

        Label_Kira.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Kira.setForeground(new java.awt.Color(255, 255, 255));
        Label_Kira.setText("Yoshikage Kira");
        getContentPane().add(Label_Kira, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 380, -1, -1));

        Label_Kars.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Kars.setForeground(new java.awt.Color(255, 255, 255));
        Label_Kars.setText("Kars");
        getContentPane().add(Label_Kars, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        Label_Dio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Dio.setForeground(new java.awt.Color(255, 255, 255));
        Label_Dio.setText("Dio Brando");
        getContentPane().add(Label_Dio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, -1, -1));

        Label_Jolyne.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        Label_Jolyne.setForeground(new java.awt.Color(255, 255, 255));
        Label_Jolyne.setText("Jolyne Kujo");
        getContentPane().add(Label_Jolyne, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 720, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonLancerPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonLancerPartieActionPerformed
        // TODO add your handling code here:
        FenetreDeJeu jeu = new FenetreDeJeu(ListeJoueurs[0], ListeJoueurs[1]);
        jeu.setVisible(true);
        Fenetre_choixJoueurs.super.dispose();
    }//GEN-LAST:event_BoutonLancerPartieActionPerformed

    private void Bouton_JonathanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JonathanActionPerformed
        // TODO add your handling code here:
        Joueur Jonathan = new Joueur("Jonathan","Joestar",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Jonathan;
        Bouton_Jonathan.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Jonathan Joestar");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Jonathan Joestar");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_JonathanActionPerformed

    private void Bouton_JosephActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JosephActionPerformed
        // TODO add your handling code here:
        Joueur Joseph = new Joueur("Joseph","Joestar",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Joseph;
        Bouton_Joseph.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Joseph Joestar");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Joseph Joestar");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_JosephActionPerformed

    private void Bouton_JotaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JotaroActionPerformed
        // TODO add your handling code here:
        Joueur Jotaro = new Joueur("Jotaro","Kujo",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Jotaro;
        Bouton_Jotaro.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Jotaro Kujo");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Jotaro Kujo");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_JotaroActionPerformed

    private void Bouton_JosukeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JosukeActionPerformed
        // TODO add your handling code here:
        Joueur Josuke = new Joueur("Josuke","Higashikata",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Josuke;
        Bouton_Josuke.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Josuke Higashikata");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Josuke Higashikata");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_JosukeActionPerformed

    private void Bouton_GiornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_GiornoActionPerformed
        // TODO add your handling code here:
        Joueur Giorno = new Joueur("Giorno","Giovanna",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Giorno;
        Bouton_Giorno.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Giorno Giovanna");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Giorno Giovanna");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_GiornoActionPerformed

    private void Bouton_JolyneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JolyneActionPerformed
        // TODO add your handling code here:
        Joueur Jolyne = new Joueur("Jolyne","Kujo",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Jolyne;
        Bouton_Jolyne.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Jolyne Kujo");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Jolyne Kujo");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_JolyneActionPerformed

    private void Bouton_DioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_DioActionPerformed
        // TODO add your handling code here:
        Joueur Dio = new Joueur("Dio","Brando",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Dio;
        Bouton_Dio.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Dio Brando");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Dio Brando");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_DioActionPerformed

    private void Bouton_KarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_KarsActionPerformed
        // TODO add your handling code here:
        Joueur Kars = new Joueur("Kars","",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Kars;
        Bouton_Kars.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Kars");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Kars");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_KarsActionPerformed

    private void Bouton_KiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_KiraActionPerformed
        // TODO add your handling code here:
        Joueur Kira = new Joueur("Yoshikage","Kira",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Kira;
        Bouton_Kira.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Yoshikage Kira");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Yoshikage Kira");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_KiraActionPerformed

    private void Bouton_DiavoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_DiavoloActionPerformed
        // TODO add your handling code here:
        Joueur Diavolo = new Joueur("Diavolo","",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Diavolo;
        Bouton_Diavolo.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Diavolo");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Diavolo");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_DiavoloActionPerformed

    private void Bouton_PucciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_PucciActionPerformed
        // TODO add your handling code here:
        Joueur Pucci = new Joueur("Enrico","Pucci",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Pucci;
        Bouton_Pucci.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Enrico Pucci");
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Enrico Pucci");
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_PucciActionPerformed

    public void BloquerBoutons() {
        if (cptJoueurs >= 2) {
            Bouton_Jonathan.setEnabled(false);
            Bouton_Joseph.setEnabled(false);
            Bouton_Jotaro.setEnabled(false);
            Bouton_Josuke.setEnabled(false);
            Bouton_Giorno.setEnabled(false);
            Bouton_Jolyne.setEnabled(false);
            Bouton_Dio.setEnabled(false);
            Bouton_Kars.setEnabled(false);
            Bouton_Kira.setEnabled(false);
            Bouton_Diavolo.setEnabled(false);
            Bouton_Pucci.setEnabled(false);
            BoutonLancerPartie.setEnabled(true);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_choixJoueurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_choixJoueurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_choixJoueurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_choixJoueurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre_choixJoueurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BoutonLancerPartie;
    private javax.swing.JButton Bouton_Diavolo;
    private javax.swing.JButton Bouton_Dio;
    private javax.swing.JButton Bouton_Giorno;
    private javax.swing.JButton Bouton_Jolyne;
    private javax.swing.JButton Bouton_Jonathan;
    private javax.swing.JButton Bouton_Joseph;
    private javax.swing.JButton Bouton_Josuke;
    private javax.swing.JButton Bouton_Jotaro;
    private javax.swing.JButton Bouton_Kars;
    private javax.swing.JButton Bouton_Kira;
    private javax.swing.JButton Bouton_Pucci;
    private javax.swing.JLabel LabelJ1;
    private javax.swing.JLabel LabelJ2;
    private javax.swing.JLabel LabelJoueur1;
    private javax.swing.JLabel LabelJoueur2;
    private javax.swing.JLabel Label_Diavolo;
    private javax.swing.JLabel Label_Dio;
    private javax.swing.JLabel Label_Giorno;
    private javax.swing.JLabel Label_Jolyne;
    private javax.swing.JLabel Label_Jonathan;
    private javax.swing.JLabel Label_Joseph;
    private javax.swing.JLabel Label_Josuke;
    private javax.swing.JLabel Label_Jotaro;
    private javax.swing.JLabel Label_Kars;
    private javax.swing.JLabel Label_Kira;
    private javax.swing.JLabel Label_Pucci;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
