/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onitama_thievon;

import javax.accessibility.AccessibleContext;
import javax.swing.JRootPane;

/**
 *
 * @author thiev
 */
public class Fenetre_choixJoueurs extends javax.swing.JFrame {
    
    Joueur[] ListeJoueurs = new Joueur[2];
    int cptJoueurs = 0;
    /**
     * Creates new form Fenetre_choixJoueurs
     */
    public Fenetre_choixJoueurs() {
        initComponents();
        BoutonLancerPartie.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        Bouton_Jolyne = new javax.swing.JButton();
        Bouton_Jonathan = new javax.swing.JButton();
        Bouton_Joseph = new javax.swing.JButton();
        Bouton_Jotaro = new javax.swing.JButton();
        Bouton_Josuke = new javax.swing.JButton();
        Bouton_Giorno = new javax.swing.JButton();
        Bouton_Pucci = new javax.swing.JButton();
        Bouton_Dio = new javax.swing.JButton();
        Bouton_Kars = new javax.swing.JButton();
        Bouton_Kira = new javax.swing.JButton();
        Bouton_Diavolo = new javax.swing.JButton();
        LabelJoueurCourant = new javax.swing.JLabel();
        LabelJoueurCourant2 = new javax.swing.JLabel();
        LabelNomJoueurCourant2 = new javax.swing.JLabel();
        LabelGifJ1 = new javax.swing.JLabel();
        LabelGifJ2 = new javax.swing.JLabel();
        LabelNomJoueurCourant = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        BoutonLancerPartie = new javax.swing.JToggleButton();
        LabelJoueur1 = new javax.swing.JLabel();
        LabelJoueur2 = new javax.swing.JLabel();
        LabelJ1 = new javax.swing.JLabel();
        LabelJ2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setText("Jotaro Kujo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bouton_Jolyne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jolyne_pt.jpg"))); // NOI18N
        Bouton_Jolyne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_JolyneMouseEntered(evt);
            }
        });
        Bouton_Jolyne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JolyneActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Jolyne, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 840, -1, -1));

        Bouton_Jonathan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jonathan_pt.jpg"))); // NOI18N
        Bouton_Jonathan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_JonathanMouseEntered(evt);
            }
        });
        Bouton_Jonathan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JonathanActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Jonathan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 840, -1, -1));

        Bouton_Joseph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Joseph_pt.jpg"))); // NOI18N
        Bouton_Joseph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_JosephMouseEntered(evt);
            }
        });
        Bouton_Joseph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JosephActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Joseph, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 840, -1, -1));

        Bouton_Jotaro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jotaro_pt.jpg"))); // NOI18N
        Bouton_Jotaro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_JotaroMouseEntered(evt);
            }
        });
        Bouton_Jotaro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JotaroActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Jotaro, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 840, -1, -1));

        Bouton_Josuke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Josuke_pt.jpg"))); // NOI18N
        Bouton_Josuke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_JosukeMouseEntered(evt);
            }
        });
        Bouton_Josuke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_JosukeActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Josuke, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 840, -1, -1));

        Bouton_Giorno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Giorno_pt.jpg"))); // NOI18N
        Bouton_Giorno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_GiornoMouseEntered(evt);
            }
        });
        Bouton_Giorno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_GiornoActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Giorno, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 840, -1, -1));

        Bouton_Pucci.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pucci_pt.jpg"))); // NOI18N
        Bouton_Pucci.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_PucciMouseEntered(evt);
            }
        });
        Bouton_Pucci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_PucciActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Pucci, new org.netbeans.lib.awtextra.AbsoluteConstraints(1730, 840, -1, -1));

        Bouton_Dio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dio_pt.jpg"))); // NOI18N
        Bouton_Dio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_DioMouseEntered(evt);
            }
        });
        Bouton_Dio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_DioActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Dio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 840, -1, -1));

        Bouton_Kars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kars_pt.jpg"))); // NOI18N
        Bouton_Kars.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_KarsMouseEntered(evt);
            }
        });
        Bouton_Kars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_KarsActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Kars, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 840, -1, -1));

        Bouton_Kira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kira_pt.jpg"))); // NOI18N
        Bouton_Kira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_KiraMouseEntered(evt);
            }
        });
        Bouton_Kira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_KiraActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Kira, new org.netbeans.lib.awtextra.AbsoluteConstraints(1390, 840, -1, -1));

        Bouton_Diavolo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Diavolo_pt.jpg"))); // NOI18N
        Bouton_Diavolo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Bouton_DiavoloMouseEntered(evt);
            }
        });
        Bouton_Diavolo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_DiavoloActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Diavolo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1560, 840, -1, -1));

        LabelJoueurCourant.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabelJoueurCourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 50, 720, 720));

        LabelJoueurCourant2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabelJoueurCourant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 50, 720, 720));

        LabelNomJoueurCourant2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        LabelNomJoueurCourant2.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabelNomJoueurCourant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 0, 380, 40));
        getContentPane().add(LabelGifJ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 51, 480, 250));
        getContentPane().add(LabelGifJ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 301, 480, 250));

        LabelNomJoueurCourant.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        LabelNomJoueurCourant.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(LabelNomJoueurCourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 370, 40));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        BoutonLancerPartie.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BoutonLancerPartie.setText("Lancer une partie");
        BoutonLancerPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonLancerPartieActionPerformed(evt);
            }
        });

        LabelJoueur1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        LabelJoueur1.setForeground(new java.awt.Color(255, 255, 255));
        LabelJoueur1.setText("Joueur 1 :");

        LabelJoueur2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        LabelJoueur2.setForeground(new java.awt.Color(255, 255, 255));
        LabelJoueur2.setText("Joueur 2 :");

        LabelJ1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        LabelJ1.setForeground(new java.awt.Color(255, 255, 255));

        LabelJ2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        LabelJ2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelJoueur1)
                            .addComponent(LabelJoueur2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelJ2)
                            .addComponent(LabelJ1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(BoutonLancerPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJoueur1)
                    .addComponent(LabelJ1))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJoueur2)
                    .addComponent(LabelJ2))
                .addGap(29, 29, 29)
                .addComponent(BoutonLancerPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 550, 480, 220));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1920, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bouton_JonathanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JonathanActionPerformed
        // TODO add your handling code here:
        Joueur Jonathan = new Joueur("Jonathan","Joestar",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Jonathan;
        Bouton_Jonathan.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Jonathan Joestar");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jonathan.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Jonathan Joestar");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jonathan.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_JonathanActionPerformed

    private void Bouton_JosephActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JosephActionPerformed
        // TODO add your handling code here:
        Joueur Joseph = new Joueur("Joseph","Joestar",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Joseph;
        Bouton_Joseph.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Joseph Joestar");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Joseph.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Joseph Joestar");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Joseph.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_JosephActionPerformed

    private void Bouton_JotaroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JotaroActionPerformed
        // TODO add your handling code here:
        Joueur Jotaro = new Joueur("Jotaro","Kujo",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Jotaro;
        Bouton_Jotaro.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Jotaro Kujo");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jotaro.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Jotaro Kujo");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jotaro.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_JotaroActionPerformed

    private void Bouton_JosukeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JosukeActionPerformed
        // TODO add your handling code here:
        Joueur Josuke = new Joueur("Josuke","Higashikata",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Josuke;
        Bouton_Josuke.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Josuke Higashikata");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Josuke.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Josuke Higashikata");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Josuke.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_JosukeActionPerformed

    private void Bouton_GiornoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_GiornoActionPerformed
        // TODO add your handling code here:
        Joueur Giorno = new Joueur("Giorno","Giovanna",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Giorno;
        Bouton_Giorno.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Giorno Giovanna");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Giorno.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Giorno Giovanna");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Giorno.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_GiornoActionPerformed

    private void Bouton_JolyneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_JolyneActionPerformed
        // TODO add your handling code here:
        Joueur Jolyne = new Joueur("Jolyne","Kujo",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Jolyne;
        Bouton_Jolyne.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Jolyne Kujo");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jolyne.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Jolyne Kujo");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jolyne.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_JolyneActionPerformed

    private void Bouton_DioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_DioActionPerformed
        // TODO add your handling code here:
        Joueur Dio = new Joueur("Dio","Brando",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Dio;
        Bouton_Dio.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Dio Brando");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dio_2.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Dio Brando");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dio_2.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_DioActionPerformed

    private void Bouton_KarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_KarsActionPerformed
        // TODO add your handling code here:
        Joueur Kars = new Joueur("Kars","",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Kars;
        Bouton_Kars.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Kars");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kars.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Kars");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kars.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_KarsActionPerformed

    private void Bouton_KiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_KiraActionPerformed
        // TODO add your handling code here:
        Joueur Kira = new Joueur("Yoshikage","Kira",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Kira;
        Bouton_Kira.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Yoshikage Kira");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kira.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Yoshikage Kira");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kira.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_KiraActionPerformed

    private void Bouton_DiavoloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_DiavoloActionPerformed
        // TODO add your handling code here:
        Joueur Diavolo = new Joueur("Diavolo","",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Diavolo;
        Bouton_Diavolo.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Diavolo");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Diavolo.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Diavolo");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Diavolo.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_DiavoloActionPerformed

    private void Bouton_PucciActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_PucciActionPerformed
        // TODO add your handling code here:
        Joueur Pucci = new Joueur("Enrico","Pucci",cptJoueurs);
        ListeJoueurs[cptJoueurs] = Pucci;
        Bouton_Pucci.setEnabled(false);
        if (cptJoueurs == 0) {
            LabelJ1.setText("Enrico Pucci");
            LabelGifJ1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pucci.gif")));
        }
        if (cptJoueurs == 1) {
            LabelJ2.setText("Enrico Pucci");
            LabelGifJ2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pucci.gif")));
        }
        cptJoueurs += 1;
        BloquerBoutons();
    }//GEN-LAST:event_Bouton_PucciActionPerformed

    private void Bouton_JonathanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_JonathanMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jonathan_gt.jpg")));
            LabelNomJoueurCourant.setText("Jonathan Joestar");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jonathan_gt.jpg")));
            LabelNomJoueurCourant2.setText("Jonathan Joestar");
        }
    }//GEN-LAST:event_Bouton_JonathanMouseEntered

    private void Bouton_JosephMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_JosephMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Joseph_gt.jpg")));
            LabelNomJoueurCourant.setText("Joseph Joestar");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Joseph_gt.jpg")));
            LabelNomJoueurCourant2.setText("Joseph Joestar");
        }
    }//GEN-LAST:event_Bouton_JosephMouseEntered

    private void Bouton_JotaroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_JotaroMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jotaro_gt.jpg")));
            LabelNomJoueurCourant.setText("Jotaro Kujo");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jotaro_gt.jpg")));
            LabelNomJoueurCourant2.setText("Jotaro Kujo");
        }
    }//GEN-LAST:event_Bouton_JotaroMouseEntered

    private void Bouton_JosukeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_JosukeMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Josuke_gt.jpg")));
            LabelNomJoueurCourant.setText("Josuke Higashikata");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Josuke_gt.jpg")));
            LabelNomJoueurCourant2.setText("Josuke Higashikata");
        }
    }//GEN-LAST:event_Bouton_JosukeMouseEntered

    private void Bouton_GiornoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_GiornoMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Giorno_gt.jpg")));
            LabelNomJoueurCourant.setText("Giorno Giovanna");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Giorno_gt.jpg")));
            LabelNomJoueurCourant2.setText("Giorno Giovanna");
        }
    }//GEN-LAST:event_Bouton_GiornoMouseEntered

    private void Bouton_DioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_DioMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dio_gt.jpg")));
            LabelNomJoueurCourant.setText("Dio Brando");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Dio_gt.jpg")));
            LabelNomJoueurCourant2.setText("Dio Brando");
        }
    }//GEN-LAST:event_Bouton_DioMouseEntered

    private void Bouton_KarsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_KarsMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kars_gt.jpg")));
            LabelNomJoueurCourant.setText("Kars");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kars_gt.jpg")));
            LabelNomJoueurCourant2.setText("Kars");
        }
    }//GEN-LAST:event_Bouton_KarsMouseEntered

    private void Bouton_KiraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_KiraMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kira_gt.jpg")));
            LabelNomJoueurCourant.setText("Yoshikage Kira");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Kira_gt.jpg")));
            LabelNomJoueurCourant2.setText("Yoshikage Kira");
        }
    }//GEN-LAST:event_Bouton_KiraMouseEntered

    private void Bouton_DiavoloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_DiavoloMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Diavolo_gt.jpg")));
            LabelNomJoueurCourant.setText("Diavolo");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Diavolo_gt.jpg")));
            LabelNomJoueurCourant2.setText("Diavolo");
        }
    }//GEN-LAST:event_Bouton_DiavoloMouseEntered

    private void Bouton_JolyneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_JolyneMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jolyne_gt.jpg")));
            LabelNomJoueurCourant.setText("Jolyne Kujo");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jolyne_gt.jpg")));
            LabelNomJoueurCourant2.setText("Jolyne Kujo");
        }
    }//GEN-LAST:event_Bouton_JolyneMouseEntered

    private void Bouton_PucciMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Bouton_PucciMouseEntered
        // TODO add your handling code here:
        if (cptJoueurs == 0) {
            LabelJoueurCourant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pucci_gt.jpg")));
            LabelNomJoueurCourant.setText("Enrico Pucci");
        }
        if (cptJoueurs == 1) {
            LabelJoueurCourant2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Pucci_gt.jpg")));
            LabelNomJoueurCourant2.setText("Enrico Pucci");
        }
    }//GEN-LAST:event_Bouton_PucciMouseEntered

    private void BoutonLancerPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonLancerPartieActionPerformed
        // TODO add your handling code here:
        FenetreDeJeu jeu = new FenetreDeJeu(ListeJoueurs[0], ListeJoueurs[1]);
        jeu.setVisible(true);
        Fenetre_choixJoueurs.super.dispose();
    }//GEN-LAST:event_BoutonLancerPartieActionPerformed

    public void BloquerBoutons() {
        if (cptJoueurs >= 2) {
            Bouton_Jonathan.setEnabled(false);
            Bouton_Joseph.setEnabled(false);
            Bouton_Jotaro.setEnabled(false);
            Bouton_Josuke.setEnabled(false);
            Bouton_Giorno.setEnabled(false);
            Bouton_Jolyne.setEnabled(false);
            Bouton_Dio.setEnabled(false);
            Bouton_Kars.setEnabled(false);
            Bouton_Kira.setEnabled(false);
            Bouton_Diavolo.setEnabled(false);
            Bouton_Pucci.setEnabled(false);
            BoutonLancerPartie.setEnabled(true);
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_choixJoueurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_choixJoueurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_choixJoueurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_choixJoueurs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre_choixJoueurs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BoutonLancerPartie;
    private javax.swing.JButton Bouton_Diavolo;
    private javax.swing.JButton Bouton_Dio;
    private javax.swing.JButton Bouton_Giorno;
    private javax.swing.JButton Bouton_Jolyne;
    private javax.swing.JButton Bouton_Jonathan;
    private javax.swing.JButton Bouton_Joseph;
    private javax.swing.JButton Bouton_Josuke;
    private javax.swing.JButton Bouton_Jotaro;
    private javax.swing.JButton Bouton_Kars;
    private javax.swing.JButton Bouton_Kira;
    private javax.swing.JButton Bouton_Pucci;
    private javax.swing.JLabel LabelGifJ1;
    private javax.swing.JLabel LabelGifJ2;
    private javax.swing.JLabel LabelJ1;
    private javax.swing.JLabel LabelJ2;
    private javax.swing.JLabel LabelJoueur1;
    private javax.swing.JLabel LabelJoueur2;
    private javax.swing.JLabel LabelJoueurCourant;
    private javax.swing.JLabel LabelJoueurCourant2;
    private javax.swing.JLabel LabelNomJoueurCourant;
    private javax.swing.JLabel LabelNomJoueurCourant2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
