/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onitama_thievon;

/**
 *
 * @author thiev
 */
public class Fenetre_Accueil extends javax.swing.JFrame {
    
    /**
     * Creates new form Fenetre_Accueil
     */
    public Fenetre_Accueil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoutonChoixPersos = new javax.swing.JToggleButton();
        jButton9 = new javax.swing.JButton();
        Jojo = new javax.swing.JLabel();
        BoutonRegle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BoutonMusique = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BoutonChoixPersos.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BoutonChoixPersos.setText("Choix des personnages");
        BoutonChoixPersos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonChoixPersosActionPerformed(evt);
            }
        });
        getContentPane().add(BoutonChoixPersos, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 250, 80));

        jButton9.setText("jButton9");
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1782, 1206, -1, -1));

        Jojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Jojo.png"))); // NOI18N
        getContentPane().add(Jojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        BoutonRegle.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BoutonRegle.setText("Règles du jeu");
        BoutonRegle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonRegleActionPerformed(evt);
            }
        });
        getContentPane().add(BoutonRegle, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, 250, 70));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 48)); // NOI18N
        jLabel1.setText("Onitama");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, -1, -1));

        BoutonMusique.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        BoutonMusique.setText("Musiques");
        BoutonMusique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoutonMusiqueActionPerformed(evt);
            }
        });
        getContentPane().add(BoutonMusique, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 730, 250, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BoutonChoixPersosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonChoixPersosActionPerformed
        // TODO add your handling code here:
        Fenetre_choixJoueurs fenetre = new Fenetre_choixJoueurs();
        fenetre.setVisible(true);
        Fenetre_Accueil.super.dispose();
    }//GEN-LAST:event_BoutonChoixPersosActionPerformed

    private void BoutonRegleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonRegleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoutonRegleActionPerformed

    private void BoutonMusiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoutonMusiqueActionPerformed
        // TODO add your handling code here:
        FenetreMusique musique = new FenetreMusique();
        musique.setVisible(true);
    }//GEN-LAST:event_BoutonMusiqueActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre_Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BoutonChoixPersos;
    private javax.swing.JButton BoutonMusique;
    private javax.swing.JButton BoutonRegle;
    private javax.swing.JLabel Jojo;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
