/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sp4_console_thievon;

/**
 *
 * @author thiev
 */
public class FenetreDeJeu extends javax.swing.JFrame {

    /**
     * Creates new form FenetreDeJeu
     */
    public FenetreDeJeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_grilleJeu = new javax.swing.JPanel();
        Panel_joueurs = new javax.swing.JPanel();
        Panel_infoJoueurs = new javax.swing.JPanel();
        Panel_infoPartie = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_grilleJeu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout Panel_grilleJeuLayout = new javax.swing.GroupLayout(Panel_grilleJeu);
        Panel_grilleJeu.setLayout(Panel_grilleJeuLayout);
        Panel_grilleJeuLayout.setHorizontalGroup(
            Panel_grilleJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        Panel_grilleJeuLayout.setVerticalGroup(
            Panel_grilleJeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_grilleJeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 480, 540));

        Panel_joueurs.setBackground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout Panel_joueursLayout = new javax.swing.GroupLayout(Panel_joueurs);
        Panel_joueurs.setLayout(Panel_joueursLayout);
        Panel_joueursLayout.setHorizontalGroup(
            Panel_joueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        Panel_joueursLayout.setVerticalGroup(
            Panel_joueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_joueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 80, 200, -1));

        Panel_infoJoueurs.setBackground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout Panel_infoJoueursLayout = new javax.swing.GroupLayout(Panel_infoJoueurs);
        Panel_infoJoueurs.setLayout(Panel_infoJoueursLayout);
        Panel_infoJoueursLayout.setHorizontalGroup(
            Panel_infoJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        Panel_infoJoueursLayout.setVerticalGroup(
            Panel_infoJoueursLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_infoJoueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        Panel_infoPartie.setBackground(new java.awt.Color(102, 255, 204));

        javax.swing.GroupLayout Panel_infoPartieLayout = new javax.swing.GroupLayout(Panel_infoPartie);
        Panel_infoPartie.setLayout(Panel_infoPartieLayout);
        Panel_infoPartieLayout.setHorizontalGroup(
            Panel_infoPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        Panel_infoPartieLayout.setVerticalGroup(
            Panel_infoPartieLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(Panel_infoPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, -1));

        setBounds(0, 0, 1096, 728);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_grilleJeu;
    private javax.swing.JPanel Panel_infoJoueurs;
    private javax.swing.JPanel Panel_infoPartie;
    private javax.swing.JPanel Panel_joueurs;
    // End of variables declaration//GEN-END:variables
}
