/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package sp4_console_thievon;


import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JOptionPane;

/**
 *
 * @author thiev
 */
public class FenetreDeJeu extends javax.swing.JFrame {
    Joueur[] ListeJoueurs = new Joueur[2];
    Joueur joueurCourant = ListeJoueurs[0];
    PlateauDeJeu grilleJeu = new PlateauDeJeu();
    /**
     * Creates new form FenetreDeJeu
     */
    public FenetreDeJeu() {
        initComponents();
        Panel_infoJoueurs.setVisible(false);
        Panel_infoPartie.setVisible(false);
        Bouton_ArreterTemps.setVisible(false);
        Bouton_Musique.setVisible(false);
        
        for (int i = 0; i<6; i++) {
            for (int j = 0; j<7; j++) {
                CelluleGraphique cellGraph = new CelluleGraphique(grilleJeu.grille[i][j]);
                
                cellGraph.addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {  
                        CelluleDeGrille c = cellGraph.celluleAssociee;
                        if (c.presenceJeton() == false) {
                            return;
                        }
                        if (c.lireCouleurDuJeton() == joueurCourant.couleur) {
                            TextMessage.setText(joueurCourant + " récupere un jeton !");
                            Jeton jrecup = c.recupererJeton();
                            joueurCourant.ajouterJeton(jrecup);
                            joueurSuivant();
                        }
                        else {
                            if (joueurCourant.nombreDesintegrateurs > 0) {
                            TextMessage.setText(joueurCourant + " a supprimé un jeton à l'aide de son stand !");
                            c.supprimerJeton();
                            joueurCourant.nombreDesintegrateurs -= 1;
                            Label_SP.setText(ListeJoueurs[0].nombreDesintegrateurs + "");
                            Label_TW.setText(ListeJoueurs[1].nombreDesintegrateurs + "");
                            if (joueurCourant.toString() == "Jotaro") {
                                PlayMusic("Star-Platinium.wav");
                            }
                            if (joueurCourant.toString() == "Dio") {
                                PlayMusic("The-World.wav");
                            }
                            joueurSuivant();
                            }
                            else {
                                return;
                            }
                        }
                        grilleJeu.tasserGrille();
                        DebloquerBoutonColonne();
                        Panel_grilleJeu.repaint();
                        boolean victoireJotaro = grilleJeu.etreGagnantePourCouleur("Rouge");
                        boolean victoireDio = grilleJeu.etreGagnantePourCouleur("Jaune");
        
                        if (victoireJotaro && ! victoireDio) {
                            FenetreFinDeJeu Fin = new FenetreFinDeJeu();
                            FenetreDeJeu.super.dispose();
                            Fin.setVisible(true);
                        }
                        if (victoireDio && ! victoireJotaro) {
                            FenetreFinDeJeu2 Fin = new FenetreFinDeJeu2();
                            FenetreDeJeu.super.dispose();
                            Fin.setVisible(true);
                        }
                        if (victoireJotaro && victoireDio) {
                            if (joueurCourant == ListeJoueurs[0]) {
                                FenetreFinDeJeu Fin = new FenetreFinDeJeu();
                                FenetreDeJeu.super.dispose();
                                Fin.setVisible(true);
                            }
                            else {
                                FenetreFinDeJeu2 Fin = new FenetreFinDeJeu2();
                                FenetreDeJeu.super.dispose();
                                Fin.setVisible(true);
                            }
                        }
                    }    
                });
                Panel_grilleJeu.add(cellGraph);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_grilleJeu = new javax.swing.JPanel();
        Panel_infoJoueurs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        Label_SP = new javax.swing.JLabel();
        Label_TW = new javax.swing.JLabel();
        Panel_LancerPartie = new javax.swing.JPanel();
        Bouton_LancerPartie = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Bouton_regle = new javax.swing.JButton();
        Panel_infoPartie = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextMessage = new javax.swing.JTextArea();
        Label_joueurCourant = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        Photo_JotaroVsDio = new javax.swing.JLabel();
        Bouton_ArreterTemps = new javax.swing.JButton();
        Photo_JojoLogo = new javax.swing.JLabel();
        Bouton_Musique = new javax.swing.JButton();
        Panel_FondNoir = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(new java.awt.Color(51, 51, 51));
        setMaximumSize(new java.awt.Dimension(1920, 1080));
        setMinimumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_grilleJeu.setBackground(new java.awt.Color(255, 255, 255));
        Panel_grilleJeu.setLayout(new java.awt.GridLayout(6, 7));
        getContentPane().add(Panel_grilleJeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 854, 732));

        Panel_infoJoueurs.setBackground(new java.awt.Color(51, 51, 51));
        Panel_infoJoueurs.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Infos joueurs :");
        Panel_infoJoueurs.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("Dio :");
        Panel_infoJoueurs.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Nombre d'utilisations de The World : ");
        Panel_infoJoueurs.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Couleur : Jaune");
        Panel_infoJoueurs.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 130, 20));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 0, 204));
        jLabel6.setText("Jotaro :");
        Panel_infoJoueurs.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 0, 204));
        jLabel7.setText("Couleur : Violet");
        Panel_infoJoueurs.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 130, 20));

        jLabel8.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 0, 204));
        jLabel8.setText("Nombre d'utilisations de Star Platinium : ");
        Panel_infoJoueurs.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));
        Panel_infoJoueurs.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 370, 10));

        Label_SP.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Label_SP.setForeground(new java.awt.Color(204, 0, 204));
        Label_SP.setText("nbSP");
        Panel_infoJoueurs.add(Label_SP, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, -1, -1));

        Label_TW.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Label_TW.setForeground(new java.awt.Color(255, 255, 0));
        Label_TW.setText("nbTW");
        Panel_infoJoueurs.add(Label_TW, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        getContentPane().add(Panel_infoJoueurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 240, 430, 290));

        Panel_LancerPartie.setBackground(new java.awt.Color(51, 51, 51));
        Panel_LancerPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bouton_LancerPartie.setBackground(new java.awt.Color(0, 0, 0));
        Bouton_LancerPartie.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Bouton_LancerPartie.setForeground(new java.awt.Color(255, 255, 255));
        Bouton_LancerPartie.setText("Lancer partie");
        Bouton_LancerPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_LancerPartieActionPerformed(evt);
            }
        });
        Panel_LancerPartie.add(Bouton_LancerPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 170, 70));

        jLabel10.setFont(new java.awt.Font("Calibri", 1, 42)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Jojo's Bizarre Adventure Edition");
        Panel_LancerPartie.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, -1, -1));

        jLabel11.setFont(new java.awt.Font("Calibri", 1, 42)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SuperPuissance4");
        Panel_LancerPartie.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        Bouton_regle.setBackground(new java.awt.Color(0, 0, 0));
        Bouton_regle.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Bouton_regle.setForeground(new java.awt.Color(255, 255, 255));
        Bouton_regle.setText("Règles de jeu");
        Bouton_regle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_regleActionPerformed(evt);
            }
        });
        Panel_LancerPartie.add(Bouton_regle, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 170, 70));

        getContentPane().add(Panel_LancerPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 760, 190));

        Panel_infoPartie.setBackground(new java.awt.Color(51, 51, 51));
        Panel_infoPartie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Joueur courant :");
        Panel_infoPartie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Infos partie :");
        Panel_infoPartie.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        TextMessage.setColumns(20);
        TextMessage.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        TextMessage.setRows(5);
        jScrollPane1.setViewportView(TextMessage);

        Panel_infoPartie.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 390, 130));

        Label_joueurCourant.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        Label_joueurCourant.setForeground(new java.awt.Color(255, 255, 255));
        Label_joueurCourant.setText("nomJoueur");
        Panel_infoPartie.add(Label_joueurCourant, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        getContentPane().add(Panel_infoPartie, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 550, 430, 260));

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 210, -1, -1));

        jButton3.setText("3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, -1, -1));

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 210, -1, -1));

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 210, -1, -1));

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 210, -1, -1));

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 210, -1, -1));

        Photo_JotaroVsDio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JotaroDio1080.jpg"))); // NOI18N
        getContentPane().add(Photo_JotaroVsDio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Bouton_ArreterTemps.setBackground(new java.awt.Color(51, 51, 51));
        Bouton_ArreterTemps.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Bouton_ArreterTemps.setForeground(new java.awt.Color(255, 255, 255));
        Bouton_ArreterTemps.setText("Arreter le temps !");
        Bouton_ArreterTemps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_ArreterTempsActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_ArreterTemps, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 910, 430, 60));

        Photo_JojoLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/JojoBonneTaille.png"))); // NOI18N
        getContentPane().add(Photo_JojoLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1470, 0, 370, 230));

        Bouton_Musique.setBackground(new java.awt.Color(51, 51, 51));
        Bouton_Musique.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        Bouton_Musique.setForeground(new java.awt.Color(255, 255, 255));
        Bouton_Musique.setText("Musique");
        Bouton_Musique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bouton_MusiqueActionPerformed(evt);
            }
        });
        getContentPane().add(Bouton_Musique, new org.netbeans.lib.awtextra.AbsoluteConstraints(1430, 830, 430, 60));

        Panel_FondNoir.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(Panel_FondNoir, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        setBounds(0, 0, 1936, 1088);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(1);
        if (joueurCourant.toString() == "Jotaro"){
            PlayMusic("ORA.wav");
        }
        if (joueurCourant.toString() == "Dio") {
            PlayMusic("MUDA.wav");
        }
        if (grilleJeu.colonneRemplie(1) == true) {
            jButton1.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(2);
        if (joueurCourant.toString() == "Jotaro"){
            PlayMusic("ORA.wav");
        }
        if (joueurCourant.toString() == "Dio") {
            PlayMusic("MUDA.wav");
        }
        if (grilleJeu.colonneRemplie(2) == true) {
            jButton2.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(3);
        if (joueurCourant.toString() == "Jotaro"){
            PlayMusic("ORA.wav");
        }
        if (joueurCourant.toString() == "Dio") {
            PlayMusic("MUDA.wav");
        }
        if (grilleJeu.colonneRemplie(3) == true) {
            jButton3.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(4);
        if (joueurCourant.toString() == "Jotaro"){
            PlayMusic("ORA.wav");
        }
        if (joueurCourant.toString() == "Dio") {
            PlayMusic("MUDA.wav");
        }
        if (grilleJeu.colonneRemplie(4) == true) {
            jButton4.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(5);
        if (joueurCourant.toString() == "Jotaro"){
            PlayMusic("ORA.wav");
        }
        if (joueurCourant.toString() == "Dio") {
            PlayMusic("MUDA.wav");
        }
        if (grilleJeu.colonneRemplie(5) == true) {
            jButton5.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(6);
        if (joueurCourant.toString() == "Jotaro"){
            PlayMusic("ORA.wav");
        }
        if (joueurCourant.toString() == "Dio") {
            PlayMusic("MUDA.wav");
        }
        if (grilleJeu.colonneRemplie(6) == true) {
            jButton6.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        jouerDansColonne(7);
        if (joueurCourant.toString() == "Jotaro"){
            PlayMusic("ORA.wav");
        }
        if (joueurCourant.toString() == "Dio") {
            PlayMusic("MUDA.wav");
        }
        if (grilleJeu.colonneRemplie(7) == true) {
            jButton7.setEnabled(false);
        }
        joueurSuivant();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void Bouton_MusiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_MusiqueActionPerformed
        // TODO add your handling code here:
        String filepath = "JoJo's Bizarre Adventure Don't Stop Me Now.wav";
        PlayMusic(filepath);
        Bouton_Musique.setEnabled(false);
    }//GEN-LAST:event_Bouton_MusiqueActionPerformed

    private void Bouton_ArreterTempsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_ArreterTempsActionPerformed
        // TODO add your handling code here:
        PlayMusic("TimeStop.wav");
        FenetreDeJeu.super.dispose();
    }//GEN-LAST:event_Bouton_ArreterTempsActionPerformed

    private void Bouton_regleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_regleActionPerformed
        // TODO add your handling code here:
        RegleJeu regle = new RegleJeu();
        regle.setVisible(true);

    }//GEN-LAST:event_Bouton_regleActionPerformed

    private void Bouton_LancerPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bouton_LancerPartieActionPerformed
        // TODO add your handling code here:
        Panel_infoJoueurs.setVisible(true);
        Panel_infoPartie.setVisible(true);
        Bouton_ArreterTemps.setVisible(true);
        Bouton_Musique.setVisible(true);
        initialiserPartie();
        Panel_grilleJeu.repaint();
        Bouton_LancerPartie.setEnabled(false);
    }//GEN-LAST:event_Bouton_LancerPartieActionPerformed
    
    public static void PlayMusic(String location) {
        try {
            File musicPath = new File(location);
            if(musicPath.exists()) {
                AudioInputStream audioInput = AudioSystem.getAudioInputStream(musicPath);
                Clip clip = AudioSystem.getClip();
                clip.open(audioInput);
                clip.start();
            }
            else {
                System.out.println("Trouve pas le fichier");
            }
        }catch(Exception e) {
            
        }
    }
    
    public void DebloquerBoutonColonne() {
        for (int i = 1; i<8; i++) {
            if (grilleJeu.colonneRemplie(i) == false) {
                if (i == 1) {
                    if (jButton1.isEnabled() == false) {
                        jButton1.setEnabled(true);
                    }
                }
                if (i == 2) {
                    if (jButton2.isEnabled() == false) {
                        jButton2.setEnabled(true);
                    }
                }
                if (i == 3) {
                    if (jButton3.isEnabled() == false) {
                        jButton3.setEnabled(true);
                    }
                }
                if (i == 4) {
                    if (jButton4.isEnabled() == false) {
                        jButton4.setEnabled(true);
                    }
                }
                if (i == 5) {
                    if (jButton5.isEnabled() == false) {
                        jButton5.setEnabled(true);
                    }
                }
                if (i == 6) {
                    if (jButton6.isEnabled() == false) {
                        jButton6.setEnabled(true);
                    }
                }
                if (i == 7) {
                    if (jButton7.isEnabled() == false) {
                        jButton7.setEnabled(true);
                    }
                }
            }
        }
    }
    
    public boolean jouerDansColonne(int nbColonne) {
        int resultatAction;
        resultatAction = grilleJeu.ajouterJetonDansColonne(joueurCourant.reserveJeton.get(joueurCourant.reserveJeton.size()-1), nbColonne);
        Panel_grilleJeu.repaint();
        
        if (resultatAction == 999 || resultatAction == 9) {
            joueurCourant.nombreDesintegrateurs += 1;
            if (resultatAction == 999) {
                TextMessage.setText("Vanilla ice a absorbé un jeton de " + joueurCourant + " !\nMais il a gagné une utilisation de stand !");
            }
            else {
                TextMessage.setText(joueurCourant + " a gagné une utilisation de stand !");
            }
        }
        if (resultatAction == 99) {
            TextMessage.setText("Vanilla ice a absorbé un jeton de " + joueurCourant + " !");
        }
        
        Label_SP.setText(ListeJoueurs[0].nombreDesintegrateurs + "");
        Label_TW.setText(ListeJoueurs[1].nombreDesintegrateurs + "");
        
        boolean victoireJotaro = grilleJeu.etreGagnantePourCouleur("Rouge");
        boolean victoireDio = grilleJeu.etreGagnantePourCouleur("Jaune");
        
        if (victoireJotaro && ! victoireDio) {
            FenetreFinDeJeu Fin = new FenetreFinDeJeu();
            FenetreDeJeu.super.dispose();
            Fin.setVisible(true);
        }
        if (victoireDio && ! victoireJotaro) {
            FenetreFinDeJeu2 Fin = new FenetreFinDeJeu2();
            FenetreDeJeu.super.dispose();
            Fin.setVisible(true);
        }
        if (victoireJotaro && victoireDio) {
            if (joueurCourant == ListeJoueurs[0]) {
                FenetreFinDeJeu2 Fin = new FenetreFinDeJeu2();
                FenetreDeJeu.super.dispose();
                Fin.setVisible(true);
            }
            else {
                FenetreFinDeJeu Fin = new FenetreFinDeJeu();
                FenetreDeJeu.super.dispose();
                Fin.setVisible(true);
            }
        }
        
        
        if (resultatAction == 1 || resultatAction == 999) {
            return true;
        }
        else {
            return false;
        }
    }
    
    public void joueurSuivant() {
        if (joueurCourant == ListeJoueurs[0]) {
            joueurCourant = ListeJoueurs[1];
            Label_joueurCourant.setText(joueurCourant.toString());
        }
        else {
            joueurCourant = ListeJoueurs[0];
            Label_joueurCourant.setText(joueurCourant.toString());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreDeJeu().setVisible(true);
            }
        });
    }

    public void initialiserPartie() {
        
        Joueur Jotaro = new Joueur("Jotaro");
        Joueur Dio = new Joueur("Dio");
        
        ListeJoueurs[0] = Jotaro;
        ListeJoueurs[1] = Dio;
        
        int jc = (int)(Math.random()*2);
        joueurCourant = ListeJoueurs[jc];
        Label_joueurCourant.setText(joueurCourant.toString());
        
        grilleJeu.viderGrille(Jotaro, Dio);
        
        this.attribuerCouleursAuxJoueurs();
        
        Label_SP.setText(Jotaro.nombreDesintegrateurs + "");
        Label_TW.setText(Dio.nombreDesintegrateurs + "");
        
        for (int i = 0; i<30; i++) {
            Jeton jetonrouge = new Jeton("Rouge");
            Jeton jetonjaune = new Jeton("Jaune");
            ListeJoueurs[0].ajouterJeton(jetonrouge);
            ListeJoueurs[1].ajouterJeton(jetonjaune);
        }
        
        int cpttn = 0;
        int cpt = 0;
        do {
            int a = 1 + (int)(Math.random() * 6);
            int b = 1 + (int)(Math.random() * 7);
            boolean p = grilleJeu.placerTrouNoir(a, b);
            if (p == true) {
                cpttn +=1;
                cpt +=1;
                if (cpt == 1 || cpt == 2) {
                    grilleJeu.placerDesintegrateur(a, b);
                }
            }
        }while (cpttn<5);
        
        int cptd = 0;
        do {
            int c = 1 + (int)(Math.random() * 6);
            int d = 1 + (int)(Math.random() * 7);
            if (grilleJeu.presenceTrouNoir(c, d) == false) {
                boolean q = grilleJeu.placerDesintegrateur(c, d);
                if (q == true) {
                    cptd +=1;
                }
            }
        }while (cptd<3);
    }
    
    public void attribuerCouleursAuxJoueurs() {
        ListeJoueurs[0].affecterCouleur("Rouge");
        ListeJoueurs[1].affecterCouleur("Jaune");
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bouton_ArreterTemps;
    private javax.swing.JButton Bouton_LancerPartie;
    private javax.swing.JButton Bouton_Musique;
    private javax.swing.JButton Bouton_regle;
    private javax.swing.JLabel Label_SP;
    private javax.swing.JLabel Label_TW;
    private javax.swing.JLabel Label_joueurCourant;
    private javax.swing.JPanel Panel_FondNoir;
    private javax.swing.JPanel Panel_LancerPartie;
    private javax.swing.JPanel Panel_grilleJeu;
    private javax.swing.JPanel Panel_infoJoueurs;
    private javax.swing.JPanel Panel_infoPartie;
    private javax.swing.JLabel Photo_JojoLogo;
    private javax.swing.JLabel Photo_JotaroVsDio;
    private javax.swing.JTextArea TextMessage;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
